<#
.SYNOPSIS
    Rebuilds fixtures\MANIFEST.toml from what is on disk.

.DESCRIPTION
    A capture without a manifest is a set of bytes with no provenance: nobody can say which server
    version produced it, when, or whether it has been edited since. The manifest records all three,
    with a SHA-256 per file, so drift is detectable rather than assumed absent.

    Called by Capture-Fixtures.ps1. Separate so that a manifest can be regenerated - after a scrub
    is widened by hand, say - without going near the live server.

.PARAMETER Root
    The fixtures directory. Defaults to fixtures\ in the repository.

.PARAMETER ServerVersion
    What the server called itself. Defaults to whatever the existing manifest recorded, so a
    regeneration does not silently drop it.

.PARAMETER CapturedOn
    The capture date, as yyyy-MM-dd. Defaults to today.

.EXAMPLE
    powershell.exe -File scripts\Write-FixtureManifest.ps1
#>
[CmdletBinding()]
param(
    [string] $Root,
    [string] $ServerVersion,
    [string] $CapturedOn = (Get-Date -Format 'yyyy-MM-dd')
)

$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\_Boot.ps1"
Assert-BootLoaded   # a dot-sourced file that fails to parse does not stop us; this does

$repoRoot = Get-RepoRoot
if (-not $Root) { $Root = Join-Path $repoRoot 'fixtures' }
if (-not (Test-Path -LiteralPath $Root)) { throw "No fixtures directory at $Root." }

$manifestPath = Join-Path $Root 'MANIFEST.toml'

if (-not $ServerVersion -and (Test-Path -LiteralPath $manifestPath)) {
    $ServerVersion = [regex]::Match(
        (Get-Content -LiteralPath $manifestPath -Raw), 'server-version\s*=\s*"([^"]+)"'
    ).Groups[1].Value
}
if (-not $ServerVersion) { $ServerVersion = 'unknown' }

# The spec version this corpus was read against, taken from SPEC.md rather than repeated here.
$specVersion = (Get-SpecManifest)[0].Version

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('# Generated by scripts\Write-FixtureManifest.ps1. Do not edit by hand.')
$lines.Add('#')
$lines.Add('# Every file here is a byte-exact capture from a real Exchange Server, with the')
$lines.Add('# deployment''s identity redacted length-preservingly and the few fields that differ on')
$lines.Add('# every capture zeroed. Each capture''s .meta.txt itemises both.')
$lines.Add('#')
$lines.Add('# The hashes are what make drift detectable: scripts\Verify-Fixtures.ps1 re-captures')
$lines.Add('# against the live lab and compares, which is the "did the protocol change" button.')
$lines.Add('')
$lines.Add('[capture]')
$lines.Add('server-version = "' + $ServerVersion + '"')
$lines.Add('captured-on = "' + $CapturedOn + '"')
$lines.Add('spec-version = "' + $specVersion + '"')
$lines.Add('tool = "mapi-cli capture"')

$scenarios = @(Get-ChildItem -Path $Root -Directory -Recurse |
    Where-Object { $_.Name -ne 'raw' } |
    Where-Object { @(Get-ChildItem -Path $_.FullName -Filter '*.meta.txt' -File).Count -gt 0 } |
    Sort-Object FullName)

$total = 0

foreach ($scenario in $scenarios) {
    $name = $scenario.FullName.Substring($Root.Length).TrimStart('\', '/').Replace('\', '/')

    $lines.Add('')
    $lines.Add('[scenarios."' + $name + '"]')

    $exchanges = @(Get-ChildItem -Path $scenario.FullName -Filter '*.meta.txt' -File |
        Sort-Object Name |
        ForEach-Object { $_.Name -replace '\.meta\.txt$', '' })

    # Built by concatenation rather than by interpolating a nested quote. `"""$_"""` inside an
    # interpolated string is a PowerShell 5.1 parse error, and one that reads like a typo.
    $quoted = ($exchanges | ForEach-Object { '"' + $_ + '"' }) -join ', '
    $lines.Add('exchanges = [' + $quoted + ']')

    $lines.Add('')
    $lines.Add('[scenarios."' + $name + '".files]')

    foreach ($file in (Get-ChildItem -Path $scenario.FullName -File | Sort-Object Name)) {
        $hash = (Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash.ToLowerInvariant()
        $lines.Add('"' + $file.Name + '" = { bytes = ' + $file.Length + ', sha256 = "' + $hash + '" }')
        $total++
    }
}

# UTF-8 with no BOM and LF endings, written explicitly rather than through Set-Content: 5.1's
# -Encoding UTF8 means "with a BOM", and .gitattributes asks for LF in every .toml. Writing what
# git would store avoids a file that is rewritten by the next checkout.
[System.IO.File]::WriteAllText(
    $manifestPath,
    ($lines -join "`n") + "`n",
    (New-Object System.Text.UTF8Encoding($false))
)

Write-Ok "${manifestPath}: $($scenarios.Count) scenario(s), $total file(s), server $ServerVersion"
exit 0
